ALTER table tbl_cpe_cabecera_inter
MODIFY TXT_DMCL_FISC_EMIS varchar(200);

ALTER table tbl_cpe_cabecera_inter
MODIFY TXT_DMCL_FISC_RECEP varchar(200);

ALTER table tbl_cpe_cabecera_inter
MODIFY DATO_EXTRA_1 varchar(120);

ALTER table tbl_cpe_cabecera_inter
MODIFY DATO_EXTRA_2 varchar(120);

ALTER table tbl_cpe_cabecera_inter
MODIFY DATO_EXTRA_3 varchar(120);

ALTER table tbl_cpe_cabecera_inter
MODIFY DATO_EXTRA_4 varchar(120);

ALTER table tbl_cpe_cabecera_inter
ADD COLUMN COD_TIP_FRMPGO int;

ALTER table tbl_cpe_cabecera_inter
ADD COLUMN MNTO_CRDT_TTAL decimal(12,2);


create table tbl_credito_cuota_inter
(
CUOTA_ID_INTERMEDIA int auto_increment primary key,
NUM_CPE_INTERMEDIA int,
NUM_CUOTA int,
MNT_CRDT_CTA decimal(12,2),
FCHA_CTA datetime,
foreign key (NUM_CPE_INTERMEDIA) references tbl_cpe_cabecera_inter(NUM_CPE_INTERMEDIA)
);

USE `bd_intermedia`;
DROP procedure IF EXISTS `SEE_ITC_INSERTAR_CREDITO_CUOTA_UBL2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SEE_ITC_INSERTAR_CREDITO_CUOTA_UBL2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SEE_ITC_INSERTAR_CREDITO_CUOTA_UBL2_1`(
in pNUM_CPE INT(3),
in pNUM_CUOTA INT(3),
in pMNT_CRDT_CTA decimal(12,2),
in pFCHA_CTA datetime
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	SHOW ERRORS LIMIT 1;
	
	ROLLBACK;
	END; 
    
    DECLARE EXIT HANDLER FOR SQLWARNING
	BEGIN
	SHOW WARNINGS LIMIT 1;
	
	ROLLBACK;
	END;
	
    
	insert into  tbl_credito_cuota_inter(CUOTA_ID_INTERMEDIA,
													NUM_CPE_INTERMEDIA,
													NUM_CUOTA, 
													MNT_CRDT_CTA, 
													FCHA_CTA) 
                                                    values(
                                                    null,
										pNUM_CPE , 
										pNUM_CUOTA , 
										pMNT_CRDT_CTA,
                                        pFCHA_CTA);
END$$

DELIMITER ;
;

USE `bd_intermedia`;
DROP procedure IF EXISTS `SP_CARGAR_CABECERA_UBL_2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SP_CARGAR_CABECERA_UBL_2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SP_CARGAR_CABECERA_UBL_2_1`(in pcliente char(4))
BEGIN

	declare done int default 0;

			select NUM_CPE_INTERMEDIA, COD_TIP_CPE, COD_MND, COD_ESTADO_DOC, COD_ESTADO_SUNAT, 			
			COD_ERROR_SUNAT, COD_CLIENTE_EMIS, NUM_RUC_EMIS, NOM_RZN_SOC_EMIS, COD_TIP_NIF_EMIS, COD_LOC_EMIS,
			COD_UBI_EMIS, TXT_DMCL_FISC_EMIS, TXT_URB_EMIS, TXT_PROV_EMIS, TXT_DPTO_EMIS,
			TXT_DISTR_EMIS, TXT_SERIE, TXT_CORRELATIVO, COD_TIP_ESCENARIO, TXT_PLACA, NUM_IDEN_RECP, 
			COD_TIP_NIF_RECP, NOM_RZN_SOC_RECP, TXT_DMCL_FISC_RECEP, PORCENTAJE_DSCTO, MNT_ANTICIPO,
            TXT_SERIE_ANTICIPO, TXT_CORRELATIVO_ANTICIPO, TXT_COD_CPE_ANTICIPO,
            MNT_TOT_GRAVADAS, MNT_TOT_INAFECTAS, MNT_TOT_EXONERADAS, MNT_TOT_GRATUITAS, MNT_OTROS_CARGOS, 			
            MNT_TOT_DESC_GLOBAL, MNT_TOT_IGV, MNT_TOT_IGV_ISC, MNT_TOT_ICBPER,TIPO_PERCEPCION, 			
			MNT_TOT_BASE_IMPONIBLE, PORCENTAJE_PERCEPCION, MNT_TOT_PERCEPCION, MNT_TOT_A_PERCIBIR, MNT_TOT,
            
            MNT_TOT_DETRAC, PERCENT_DETRAC, DESCRIP_DETRAC, NUM_CTA_BN, TIP_DETRAC, INFOS_DETRAC,
				
            TXT_DESCR_MOTIVO_BAJA, COD_TIP_NC_ND_REF, TXT_CORRELATIVO_CPE_REF, TXT_SERIE_REF, COD_CPE_REF, FEC_EMIS_REF, TXT_SUSTENTO,			
			TICKET_ID_RECEP_SUNAT, COD_RPTA_ENVIO_SUNAT, FECHA_ENVIO_SUNAT, FECHA_RECP_SUNAT, FEC_GENE_DOC_SUNAT, 
			FEC_EMIS, HORA_EMIS, FEC_VENCI, FEC_RECP_DOC1, FLAG_NUM_INT, FLAG_ENVIO_BOLETAS, COD_IDEN_CB, COD_IDEN_RD, 
			COD_IDEN_COM_BAJA, FEC_GENER_BAJA, TXT_CORREO_ADQUIRIENTE, FLAG_CORREO, TXT_RESP, TIPO_CAMBIO, 
            TXT_CONDICION_PAGO, COD_MODO_PAGO, FLAG_PAGADO, COD_OPERACION, OBSERVACIONES, ORDEN_COMPRA, GUIA_REMISION, FLAG_ENVIO_AUTOMATICO,			
            			
            GUIA_TXT_COD_UBIG, GUIA_TXT_DMCL_FISC, GUIA_TXT_URB, GUIA_TXT_PROV,			
			GUIA_TXT_DPTO, GUIA_TXT_DISTR, GUIA_TXT_PAIS, GUIA_COD_UBIG_LLEGDA, GUIA_TXT_DMCL_FISC_LLEGDA, 
			GUIA_TXT_URB_LLEGDA, GUIA_TXT_PROV_LLEGDA, GUIA_TXT_DPTO_LLEGDA, GUIA_TXT_DISTR_LLEGDA, GUIA_TXT_PAIS_LLEGDA, 
            GUIA_TXT_PLACA_AUTO_TRNSP, GUIA_TXT_CERT_AUTO_TRNSP, GUIA_TXT_MARCA_AUTO_TRNSP, GUIA_TXT_LIC_COND_TRNSP, 			
            GUIA_TXT_RUC_TRNSP, GUIA_TXT_COD_OTR_TRNSP, GUIA_TXT_RZN_SCL_TRNSP, GUIA_TXT_COD_MOD_TRNSP, GUIA_MNT_TOTAL_BRUTO, 			
            GUIA_COD_UNID_MED, DATO_EXTRA_1, DATO_EXTRA_2, DATO_EXTRA_3, DATO_EXTRA_4, MARCA_EXPOR , ORIGEN_EXPOR, DESPACHO_EXPOR, 
            SOLDTO_EXPOR, SHIPTO_EXPOR, NUMEROCAJAS_EXPOR, PESOBRUTO_EXPOR, PESONETO_EXPOR, VOLUMEN_EXPOR, ESTAD_ITEM,
            COD_TIP_FRMPGO, MNTO_CRDT_TTAL
            
            from tbl_cpe_cabecera_inter where COD_CLIENTE_EMIS = pcliente 
            and TXT_FLAGCARGA='2'   LIMIT 300;
            
            
END$$

DELIMITER ;
;

USE `bd_intermedia`;
DROP procedure IF EXISTS `SP_CARGAR_CREDITO_CUOTA_INTER_UBL_2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SP_CARGAR_CREDITO_CUOTA_INTER_UBL_2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SP_CARGAR_CREDITO_CUOTA_INTER_UBL_2_1`(in pnumcpe int)
BEGIN

	 declare done int default 0;

     select NUM_CPE_INTERMEDIA, NUM_CUOTA, MNT_CRDT_CTA, 
     FCHA_CTA
     from tbl_credito_cuota_inter 
     where NUM_CPE_INTERMEDIA= pnumcpe;
END$$

DELIMITER ;
;





USE `bd_intermedia`;
DROP procedure IF EXISTS `SEE_ITC_INSERTAR_FACTURA_BOLETA_UBL2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SEE_ITC_INSERTAR_FACTURA_BOLETA_UBL2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SEE_ITC_INSERTAR_FACTURA_BOLETA_UBL2_1`(
IN pFEC_EMIS DATETIME,
IN pHORA_EMIS VARCHAR(10),
IN pTXT_SERIE CHAR(4),
IN pTXT_CORRELATIVO VARCHAR(8),
IN pCOD_TIP_CPE CHAR(2),
IN pCOD_MND CHAR(3),
IN pCOD_TIP_ESCENARIO char(2),
IN pTXT_PLACA varchar(10),
IN pCOD_CLIENTE_EMIS CHAR(4),

IN pNUM_RUC_EMIS varchar(11),
IN pNOM_RZN_SOC_EMIS varchar(100),
IN pCOD_TIP_NIF_EMIS char(1),
IN pCOD_LOC_EMIS varchar(3),

IN pCOD_UBI_EMIS varchar(6),
IN pTXT_DMCL_FISC_EMIS varchar(200),
IN pTXT_URB_EMIS varchar(25),
IN pTXT_PROV_EMIS varchar(30),
IN pTXT_DPTO_EMIS varchar(30),
IN pTXT_DISTR_EMIS varchar(30),

IN pNUM_IDEN_RECP VARCHAR(11),
IN pCOD_TIP_NIF_RECP CHAR(1),
IN pNOM_RZN_SOC_RECP VARCHAR(100),
IN pTXT_DMCL_FISC_RECEP VARCHAR(200),
IN pTXT_CORREO_ADQUIRIENTE varchar(120),
IN pMNT_TOT_GRAVADAS DECIMAL(12,2),
IN pMNT_TOT_INAFECTAS DECIMAL(12,2),
IN pMNT_TOT_EXONERADAS DECIMAL(12,2),
IN pMNT_TOT_GRATUITAS DECIMAL(12,2),
IN pMNT_TOT_DESC_GLOBAL DECIMAL(12,2),
IN pMNT_TOT_IGV DECIMAL(12,2),
IN pMNT_TOT_IGV_ISC DECIMAL(12,2),
IN pMNT_TOT_ICBPER DECIMAL(12,2),
IN pMNT_TOT_BASE_IMPONIBLE DECIMAL(12,2),
IN pMNT_TOT_PERCEPCION DECIMAL(12,2),
IN pMNT_TOT_A_PERCIBIR DECIMAL(12,2),
IN pMNT_TOT DECIMAL(12,2),
in pCOD_OPERACION varchar(4),

in pPORCENTAJE_DSCTO varchar(5), 
in pMNT_ANTICIPO decimal(12,2), 
in pMNT_OTROS_CARGOS decimal(12,2),
in pTIPO_PERCEPCION char(2), 
in pPORCENTAJE_PERCEPCION varchar(5), 
in pTIPO_CAMBIO decimal(12,2),
in pTXT_CONDICION_PAGO VARCHAR(60),  
in pFLAG_PAGADO CHAR(1), 
in pTXT_OBSERV varchar(150),
in pORDEN_COMPRA varchar(20), 
in pGUIA_REMISION varchar(50),
in pFLAG_ENVIO_AUTOMATICO char(1),
in pGUIA_TXT_COD_UBIG varchar(6), 
in pGUIA_TXT_DMCL_FISC varchar(100), 
in pGUIA_TXT_URB varchar(25),
in pGUIA_TXT_PROV varchar(30), 
in pGUIA_TXT_DPTO varchar(30), 
in pGUIA_TXT_DISTR varchar(30),
in pGUIA_TXT_PAIS char(2), 
in pGUIA_COD_UBIG_LLEGDA varchar(6), 
in pGUIA_TXT_DMCL_FISC_LLEGDA varchar(100),
in pGUIA_TXT_URB_LLEGDA varchar(25), 
in pGUIA_TXT_PROV_LLEGDA varchar(30), 
in pGUIA_TXT_DPTO_LLEGDA varchar(30),
in pGUIA_TXT_DISTR_LLEGDA varchar(30), 
in pGUIA_TXT_PAIS_LLEGDA char(2), 
in pGUIA_TXT_PLACA_AUTO_TRNSP varchar(10),
in pGUIA_TXT_CERT_AUTO_TRNSP varchar(30), 
in pGUIA_TXT_MARCA_AUTO_TRNSP varchar(50), 
in pGUIA_TXT_LIC_COND_TRNSP varchar(30),
in pGUIA_TXT_RUC_TRNSP varchar(11), 
in pGUIA_TXT_COD_OTR_TRNSP char(2), 
in pGUIA_TXT_RZN_SCL_TRNSP varchar(100),
in pGUIA_TXT_COD_MOD_TRNSP char(2), 
in pGUIA_MNT_TOTAL_BRUTO decimal(12,2), 
in pGUIA_COD_UNID_MED char(3),
in pDATO_EXTRA_1 varchar(120),
in pDATO_EXTRA_2 varchar(120),
in pDATO_EXTRA_3 varchar(120),
in pDATO_EXTRA_4 varchar(120),

in pMARCA_EXPOR varchar(25),
in pORIGEN_EXPOR VARCHAR(25),
in pDESPACHO_EXPOR VARCHAR(25),
in pSOLDTO_EXPOR VARCHAR(25),
in pSHIPTO_EXPOR VARCHAR(25),
in pNUMEROCAJAS_EXPOR varchar(15),
in pPESOBRUTO_EXPOR decimal(12,2) ,
in pPESONETO_EXPOR decimal(12,2),
in pVOLUMEN_EXPOR decimal(12,2),

in pFEC_VENCI datetime,
in pMNT_TOT_DETRAC decimal(12,2),
in pPERCENT_DETRAC varchar(5),
in pDESCRIP_DETRAC varchar(100),
in pNUM_CTA_BN varchar(20),
in pTIP_DETRAC char(1),
in pINFOS_DETRAC varchar(100),
in pTXT_SERIE_ANTICIPO char(4),
in pTXT_CORRELATIVO_ANTICIPO varchar(8),
in pTXT_COD_CPE_ANTICIPO char(2),

in pCOD_TIP_FRMPGO int,
in pMNTO_CRDT_TTAL decimal(12,2),

out num_cpe int(11),
out mensaje varchar (100),
out resultado int
)
BEGIN

declare pESTAD_ITEM char(1);
  
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
    
	SHOW ERRORS LIMIT 1;
			
	ROLLBACK;
	END; 
    
    DECLARE EXIT HANDLER FOR SQLWARNING
	BEGIN
	SHOW WARNINGS LIMIT 1;
	
	ROLLBACK;
	END;
    
	
	select count(*) into resultado from tbl_cpe_cabecera_inter where CONCAT(TXT_SERIE,'', TXT_CORRELATIVO) = CONCAT(pTXT_SERIE,'', pTXT_CORRELATIVO) AND COD_TIP_CPE = pCOD_TIP_CPE 
    AND COD_IDEN_CB <> 'C' AND NUM_RUC_EMIS = pNUM_RUC_EMIS;
	if resultado then
		set mensaje = 'Serie-correlativo ya existe';
        set num_cpe = 0;
		select resultado,  mensaje, num_cpe;
	else
	
    if(pCOD_TIP_CPE = '01') then
		set pESTAD_ITEM = '0';
    else
		set pESTAD_ITEM = '1';
    end if;
    
    
	INSERT INTO tbl_cpe_cabecera_inter(FEC_EMIS,HORA_EMIS,TXT_SERIE,TXT_CORRELATIVO,COD_TIP_CPE,COD_MND,COD_ESTADO_DOC,COD_ESTADO_SUNAT,COD_TIP_ESCENARIO,TXT_PLACA,COD_CLIENTE_EMIS, NUM_RUC_EMIS,
	NOM_RZN_SOC_EMIS, COD_TIP_NIF_EMIS, COD_LOC_EMIS, COD_UBI_EMIS, TXT_DMCL_FISC_EMIS,TXT_URB_EMIS,TXT_PROV_EMIS,TXT_DPTO_EMIS,TXT_DISTR_EMIS,NUM_IDEN_RECP,
    COD_TIP_NIF_RECP,NOM_RZN_SOC_RECP,TXT_DMCL_FISC_RECEP,TXT_CORREO_ADQUIRIENTE,FEC_RECP_DOC1,FLAG_NUM_INT,FLAG_CORREO,FLAG_ENVIO_BOLETAS,MNT_TOT_GRAVADAS,MNT_TOT_INAFECTAS,MNT_TOT_EXONERADAS,MNT_TOT_GRATUITAS,
    MNT_TOT_DESC_GLOBAL,MNT_TOT_IGV,MNT_TOT_IGV_ISC,MNT_TOT_ICBPER,MNT_TOT_BASE_IMPONIBLE,MNT_TOT_PERCEPCION,MNT_TOT_A_PERCIBIR,MNT_TOT,
    TXT_DESCR_MOTIVO_BAJA,COD_TIP_NC_ND_REF,TXT_CORRELATIVO_CPE_REF,TXT_SERIE_REF,COD_CPE_REF,TXT_SUSTENTO,COD_IDEN_CB,
	COD_IDEN_RD,COD_IDEN_COM_BAJA,TXT_RESP,TXT_FLAGCARGA, COD_OPERACION,
    
    PORCENTAJE_DSCTO, MNT_ANTICIPO, MNT_OTROS_CARGOS, TIPO_PERCEPCION,
    PORCENTAJE_PERCEPCION, TIPO_CAMBIO, TXT_CONDICION_PAGO, FLAG_PAGADO, OBSERVACIONES,
    ORDEN_COMPRA, GUIA_REMISION, FLAG_ENVIO_AUTOMATICO,
    
    GUIA_TXT_COD_UBIG, GUIA_TXT_DMCL_FISC, GUIA_TXT_URB,
	GUIA_TXT_PROV, GUIA_TXT_DPTO, GUIA_TXT_DISTR,
	GUIA_TXT_PAIS, GUIA_COD_UBIG_LLEGDA, GUIA_TXT_DMCL_FISC_LLEGDA,
	GUIA_TXT_URB_LLEGDA, GUIA_TXT_PROV_LLEGDA, GUIA_TXT_DPTO_LLEGDA,
	GUIA_TXT_DISTR_LLEGDA, GUIA_TXT_PAIS_LLEGDA, GUIA_TXT_PLACA_AUTO_TRNSP,
	GUIA_TXT_CERT_AUTO_TRNSP, GUIA_TXT_MARCA_AUTO_TRNSP, GUIA_TXT_LIC_COND_TRNSP,
	GUIA_TXT_RUC_TRNSP, GUIA_TXT_COD_OTR_TRNSP, GUIA_TXT_RZN_SCL_TRNSP,
	GUIA_TXT_COD_MOD_TRNSP, GUIA_MNT_TOTAL_BRUTO, GUIA_COD_UNID_MED,
    DATO_EXTRA_1, DATO_EXTRA_2, DATO_EXTRA_3, DATO_EXTRA_4, 
    
    MARCA_EXPOR, ORIGEN_EXPOR, DESPACHO_EXPOR, SOLDTO_EXPOR, SHIPTO_EXPOR, NUMEROCAJAS_EXPOR,
	PESOBRUTO_EXPOR , PESONETO_EXPOR, VOLUMEN_EXPOR, FEC_VENCI,
    
    MNT_TOT_DETRAC, PERCENT_DETRAC, DESCRIP_DETRAC, NUM_CTA_BN, TIP_DETRAC, INFOS_DETRAC,
    TXT_SERIE_ANTICIPO, TXT_CORRELATIVO_ANTICIPO, TXT_COD_CPE_ANTICIPO,
    ESTAD_ITEM, COD_TIP_FRMPGO, MNTO_CRDT_TTAL)
    
    values(pFEC_EMIS,pHORA_EMIS,pTXT_SERIE,pTXT_CORRELATIVO,pCOD_TIP_CPE,pCOD_MND,'03','101',pCOD_TIP_ESCENARIO,pTXT_PLACA,pCOD_CLIENTE_EMIS, pNUM_RUC_EMIS, pNOM_RZN_SOC_EMIS, pCOD_TIP_NIF_EMIS, pCOD_LOC_EMIS,
    pCOD_UBI_EMIS, pTXT_DMCL_FISC_EMIS,pTXT_URB_EMIS,pTXT_PROV_EMIS,pTXT_DPTO_EMIS,pTXT_DISTR_EMIS,pNUM_IDEN_RECP,pCOD_TIP_NIF_RECP,
    pNOM_RZN_SOC_RECP,pTXT_DMCL_FISC_RECEP,pTXT_CORREO_ADQUIRIENTE,NOW(),'0','0','0',pMNT_TOT_GRAVADAS,pMNT_TOT_INAFECTAS,pMNT_TOT_EXONERADAS,pMNT_TOT_GRATUITAS,pMNT_TOT_DESC_GLOBAL,
    pMNT_TOT_IGV,pMNT_TOT_IGV_ISC,pMNT_TOT_ICBPER,pMNT_TOT_BASE_IMPONIBLE,pMNT_TOT_PERCEPCION,pMNT_TOT_A_PERCIBIR,pMNT_TOT,
    '','','','','','','','','','0','1', pCOD_OPERACION,
    pPORCENTAJE_DSCTO, pMNT_ANTICIPO, pMNT_OTROS_CARGOS, pTIPO_PERCEPCION,
    pPORCENTAJE_PERCEPCION, pTIPO_CAMBIO, pTXT_CONDICION_PAGO, 
    pFLAG_PAGADO, pTXT_OBSERV, pORDEN_COMPRA, pGUIA_REMISION, pFLAG_ENVIO_AUTOMATICO,
    pGUIA_TXT_COD_UBIG, pGUIA_TXT_DMCL_FISC, pGUIA_TXT_URB,
	pGUIA_TXT_PROV, pGUIA_TXT_DPTO, pGUIA_TXT_DISTR,
	pGUIA_TXT_PAIS, pGUIA_COD_UBIG_LLEGDA, pGUIA_TXT_DMCL_FISC_LLEGDA,
	pGUIA_TXT_URB_LLEGDA, pGUIA_TXT_PROV_LLEGDA, pGUIA_TXT_DPTO_LLEGDA,
	pGUIA_TXT_DISTR_LLEGDA, pGUIA_TXT_PAIS_LLEGDA, pGUIA_TXT_PLACA_AUTO_TRNSP,
	pGUIA_TXT_CERT_AUTO_TRNSP, pGUIA_TXT_MARCA_AUTO_TRNSP, pGUIA_TXT_LIC_COND_TRNSP,
	pGUIA_TXT_RUC_TRNSP, pGUIA_TXT_COD_OTR_TRNSP, pGUIA_TXT_RZN_SCL_TRNSP,
	pGUIA_TXT_COD_MOD_TRNSP, pGUIA_MNT_TOTAL_BRUTO, pGUIA_COD_UNID_MED,
    pDATO_EXTRA_1, pDATO_EXTRA_2, pDATO_EXTRA_3, pDATO_EXTRA_4, 
    
    pMARCA_EXPOR, pORIGEN_EXPOR, pDESPACHO_EXPOR, pSOLDTO_EXPOR, pSHIPTO_EXPOR,
	pNUMEROCAJAS_EXPOR, pPESOBRUTO_EXPOR, pPESONETO_EXPOR, pVOLUMEN_EXPOR, pFEC_VENCI,
                    
    pMNT_TOT_DETRAC, pPERCENT_DETRAC, pDESCRIP_DETRAC, pNUM_CTA_BN, pTIP_DETRAC, pINFOS_DETRAC,
	pTXT_SERIE_ANTICIPO, pTXT_CORRELATIVO_ANTICIPO, pTXT_COD_CPE_ANTICIPO,
    pESTAD_ITEM, pCOD_TIP_FRMPGO, pMNTO_CRDT_TTAL);
 
	set num_cpe = LAST_INSERT_ID(); 
    set mensaje = 'Se ingreso correctamente';
		select resultado, mensaje, num_cpe;
    end if;

END$$

DELIMITER ;
;



-- PLUSSSSS RETENCION



create table tbl_retenciones
(
ID int auto_increment primary key,
RETENCION_CODIGO varchar(6),
RETENCION_FACTOR varchar(10),
RETENCION_BASE decimal(12,2),
RETENCION_MONTO decimal(12,2),
NUM_CPE_INTERMEDIA int
);


USE `bd_intermedia`;
DROP procedure IF EXISTS `SEE_ITC_INSERTAR_RETENCION2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SEE_ITC_INSERTAR_RETENCION2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SEE_ITC_INSERTAR_RETENCION2_1`(
pRETENCION_CODIGO varchar(6),
pRETENCION_FACTOR varchar(10),
pRETENCION_BASE decimal(12,2),
pRETENCION_MONTO decimal(12,2),
pNUM_CPE_INTERMEDIA int
)
BEGIN

	insert into tbl_retenciones values(null, pRETENCION_CODIGO, pRETENCION_FACTOR, pRETENCION_BASE, pRETENCION_MONTO, pNUM_CPE_INTERMEDIA);
    
    
END$$

DELIMITER ;
;

-- PLUSSSSS ANTICIPO


create table tbl_anticipo_inter
(
ALEATORIO_INTER int auto_increment primary key,
TXT_SERIE char(4),
TXT_CORRELATIVO varchar(8),
COD_AFECTAC_IGV varchar(3),
MONTO decimal(12,2),
COD_REL_ATRI char(2),
NUM_CPE_INTERMEDIA int,
foreign key (NUM_CPE_INTERMEDIA) references tbl_cpe_cabecera_inter(NUM_CPE_INTERMEDIA)
);





USE `bd_intermedia`;
DROP procedure IF EXISTS `SEE_ITC_INSERTAR_ANTICIPOS_UBL2_1`;

USE `bd_intermedia`;
DROP procedure IF EXISTS `bd_intermedia`.`SEE_ITC_INSERTAR_ANTICIPOS_UBL2_1`;
;

DELIMITER $$
USE `bd_intermedia`$$
CREATE DEFINER=`root`@`%` PROCEDURE `SEE_ITC_INSERTAR_ANTICIPOS_UBL2_1`(
in pTXT_SERIE char(4),
in pTXT_CORRELATIVO varchar(8),
in pCOD_AFECTAC_IGV varchar(3),
in pMONTO decimal(12,2),
in pCOD_REL_ATRI char(2),
in pNUM_CPE int
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	SHOW ERRORS LIMIT 1;
	
	ROLLBACK;
	END; 
    
    DECLARE EXIT HANDLER FOR SQLWARNING
	BEGIN
	SHOW WARNINGS LIMIT 1;
	
	ROLLBACK;
	END;
	
    
	insert into  tbl_anticipo_inter(TXT_SERIE,
													TXT_CORRELATIVO,
													COD_AFECTAC_IGV, 
													MONTO, 
													COD_REL_ATRI,
                                                    NUM_CPE_INTERMEDIA) 
                                                    values(
										pTXT_SERIE , 
										pTXT_CORRELATIVO , 
										pCOD_AFECTAC_IGV,
                                        pMONTO,
                                        pCOD_REL_ATRI,
                                        pNUM_CPE);
                                        
END$$

DELIMITER ;
;


